- name: Nginx server install and start
  hosts: om
  become: yes # Use sudo access
  vars:
    nginx_port: 80
  tasks:
    - name: Install Nginx server
      ansible.builtin.package:
        name: nginx
        state: present
      notify: 
        - start nginx

  handlers:
    - name: Start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
