- name: install configurations
  hosts: all
  become: yes
  serial: 4
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx
    tags:
    - omnamahashivaya

  - name: configure service
    ansible.builtin.service:
      name: nginx
      state: started