- name: Error Handling
  hosts: all
  become: yes
  tasks:
    - name: Fail this command
      ansible.builtin.shell:
        cmd: exit 1
      ignore_errors: true

    - name: Print Hello
      ansible.builtin.debug:
        msg: "Hello, om namaha shivaya"
