- name: check value is greater than 10 or not
  hosts: local
  connection: local
  vars:
    - my_number: 15 # list
  tasks:
    - name: if number is greater than 10
      ansible.builtin.debug:
        msg: Given number is {{ my_number }} is greater than to 10
      when: my_number > 10 # conditin ( if , else, ansible use when )

    - name: if number is less than 10
      ansible.builtin.debug:
        msg: Given number is {{ my_number }} is lessthan than to 10
      when: my_number < 10 # conditin ( if , else, ansible use when )